## Basic EDA

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
data1 = pd.read_csv("data/RawData/acc_exp01_user01.txt", sep=" ", header=None, names = ('X','Y','Z'))

In [32]:
data1

              X         Y         Z
0      0.918056 -0.112500  0.509722
1      0.911111 -0.093056  0.537500
2      0.881944 -0.086111  0.513889
3      0.881944 -0.086111  0.513889
4      0.879167 -0.100000  0.505556
...         ...       ...       ...
20593 -0.069444  0.531944  0.806944
20594 -0.061111  0.519444  0.919444
20595 -0.051389  0.516667  0.956944
20596 -0.061111  0.525000  0.956944
20597 -0.048611  0.544444  0.947222

[20598 rows x 3 columns]

In [33]:
data1.iloc[250:1232]

             X         Y         Z
250   1.020833 -0.125000  0.105556
251   1.025000 -0.125000  0.101389
252   1.020833 -0.125000  0.104167
253   1.016667 -0.125000  0.108333
254   1.018056 -0.127778  0.108333
...        ...       ...       ...
1227  1.019445 -0.134722  0.073611
1228  1.022222 -0.137500  0.077778
1229  1.025000 -0.137500  0.076389
1230  1.030556 -0.144444  0.079167
1231  1.016667 -0.143056  0.058333

[982 rows x 3 columns]

In [34]:
data1

              X         Y         Z
0      0.918056 -0.112500  0.509722
1      0.911111 -0.093056  0.537500
2      0.881944 -0.086111  0.513889
3      0.881944 -0.086111  0.513889
4      0.879167 -0.100000  0.505556
...         ...       ...       ...
20593 -0.069444  0.531944  0.806944
20594 -0.061111  0.519444  0.919444
20595 -0.051389  0.516667  0.956944
20596 -0.061111  0.525000  0.956944
20597 -0.048611  0.544444  0.947222

[20598 rows x 3 columns]

In [35]:
# experiment id, user id are to identify the participant and which experiment the data belongs to
# activity is which exercise was performed
# label start and label end are which rows of the experiment the labels belong to
rawlabelcolumns = ['exp_id','user_id','activity','label_start','label_end']

In [36]:
rawlabels = pd.read_csv("data/RawData/labels.txt", sep = ' ', header = None, names = rawlabelcolumns)

In [37]:
rawlabels

      exp_id  user_id  activity  label_start  label_end
0          1        1         5          250       1232
1          1        1         7         1233       1392
2          1        1         4         1393       2194
3          1        1         8         2195       2359
4          1        1         5         2360       3374
...      ...      ...       ...          ...        ...
1209      61       30         2        13842      14574
1210      61       30         3        14751      15427
1211      61       30         2        15588      16319
1212      61       30         3        16546      17250
1213      61       30         2        17394      18097

[1214 rows x 5 columns]

In [74]:
datalabels = pd.read_csv('data/features2.txt', header = None)

In [75]:
datalabels[datalabels.duplicated()]

Empty DataFrame
Columns: [0]
Index: []

In [72]:
X_test = pd.read_csv("data/Test/X_test.txt", sep = ' ', header = None, names = datalabels[0])

In [73]:
X_test

,tBodyAcc-Mean-1,tBodyAcc-Mean-2,tBodyAcc-Mean-3,tBodyAcc-STD-1,tBodyAcc-STD-2,tBodyAcc-STD-3,tBodyAcc-Mad-1,tBodyAcc-Mad-2,tBodyAcc-Mad-3,tBodyAcc-Max-1,...,fBodyGyroJerkMag-MeanFreq-1,fBodyGyroJerkMag-Skewness-1,fBodyGyroJerkMag-Kurtosis-1,tBodyAcc-AngleWRTGravity-1,tBodyAccJerk-AngleWRTGravity-1,tBodyGyro-AngleWRTGravity-1,tBodyGyroJerk-AngleWRTGravity-1,tXAxisAcc-AngleWRTGravity-1,tYAxisAcc-AngleWRTGravity-1,tZAxisAcc-AngleWRTGravity-1
0,0.030914,-0.008927,0.040382,-0.938504,-0.944626,-0.759334,-0.952398,-0.950281,-0.802483,-0.757099,...,0.122830,-0.345684,-0.709087,0.006462,0.162920,-0.825886,0.271151,-0.720559,0.276779,-0.051074
1,0.042548,0.001079,-0.026236,-0.975516,-0.977502,-0.960146,-0.986694,-0.978983,-0.966820,-0.757099,...,-0.314688,-0.142804,-0.600867,-0.083495,0.017500,-0.434375,0.920593,-0.698684,0.281322,-0.076825
2,0.038297,-0.011660,-0.025643,-0.993922,-0.979215,-0.973030,-0.994298,-0.980535,-0.977508,-0.799005,...,0.114730,-0.209525,-0.645500,-0.034956,0.202302,0.064103,0.145068,-0.703355,0.280062,-0.072302
3,0.036205,-0.018148,-0.025240,-0.994845,-0.981534,-0.976175,-0.995169,-0.983020,-0.980785,-0.798401,...,0.164515,-0.359352,-0.738474,-0.017067,0.154438,0.340134,0.296407,-0.699545,0.284093,-0.070079
4,0.038034,-0.013437,-0.032899,-0.993955,-0.977493,-0.984290,-0.994006,-0.977354,-0.985899,-0.798401,...,-0.056085,-0.544467,-0.846150,-0.002223,-0.040046,0.736715,-0.118545,-0.692849,0.290701,-0.066849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3157,0.052279,-0.038687,-0.013494,-0.287933,-0.403601,-0.431550,-0.356012,-0.433826,-0.534817,0.244280,...,0.125445,-0.390349,-0.752788,-0.337422,0.346295,0.884904,-0.698885,-0.652416,0.274605,0.190104
3158,0.073745,-0.024673,-0.017836,-0.305455,-0.286487,-0.417996,-0.373468,-0.354849,-0.557925,0.244280,...,0.150787,-0.336001,-0.703532,-0.736701,-0.372889,-0.657421,0.322548,-0.655858,0.273556,0.187748
3159,0.068334,0.043822,-0.024135,-0.329706,-0.335273,-0.456965,-0.387944,-0.423504,-0.604403,0.079255,...,-0.004765,-0.139894,-0.476335,-0.181560,0.088574,0.696664,0.363139,-0.656034,0.274457,0.186527
3160,0.023016,0.032345,-0.011830,-0.323182,-0.465502,-0.426108,-0.392307,-0.520848,-0.569571,0.079255,...,0.013540,-0.224141,-0.623083,0.444558,-0.819188,0.929294,-0.008398,-0.660387,0.264759,0.192865
3161,-0.010846,-0.004134,-0.037678,-0.330114,-0.441542,-0.394796,-0.430898,-0.480065,-0.533532,-0.031137,...,0.046926,-0.094539,-0.446862,0.598808,-0.287951,0.876030,-0.024965,-0.660748,0.263914,0.193402